# Posrgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
spring.datasource.username=postgres
spring.datasource.password=1234


spring.jpa.properties.hibernate.format_sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.tomcat.accesslog.enabled=true


server.port=${PORT:8080}
url.donaciones=http://localhost:8081 
url.donadoresYEntidades=http://localhost:8082
url.incentivos=http://localhost:8083
