# Posrgres Database Configuration

# local
#spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
#spring.datasource.username=postgres
#spring.datasource.password=1234

# render

spring.datasource.url=jdbc:postgresql://dpg-d9h5l5vaqgkc73aqiveg-a.oregon-postgres.render.com:5432/logistica_db_06w3?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=logistica_db_06w3_user
spring.datasource.password=VoFUZcr1aJKZ6bcvKQMeYgJ7An8S78Ii
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Datadog
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com/
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.api-key=2406e26896fe53e3e7d5b2065c723d66
management.datadog.metrics.export.applicationKey=ddapp_YlsFj6ZtIXqXlTBfVcoVtkyJPHzh4cOX6w

#management.datadog.metrics.export.uri=https://api.datadoghq.com/
#management.datadog.metrics.export.enabled=true
#management.datadog.metrics.export.step=30s
#management.datadog.metrics.export.api-key=6b4af422f0aae09dff0df439ab873c80
#management.datadog.metrics.export.applicationKey=ddapp_wR3lFSs0Pk3wUEEMpabToXyU1sFF2s1wBR

management.metrics.tags.modulo=logistica


spring.jpa.properties.hibernate.format_sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.tomcat.accesslog.enabled=true


server.port=${PORT:8080}
url.donaciones=https://donaciones-b4cs.onrender.com
url.donadoresYEntidades=https://donadoresyentidades.onrender.com
url.logistica=https://logistica-tk85.onrender.com

management.datadog.metrics.export.enabled=${DATADOG_ENABLED:false}
management.datadog.metrics.export.api-key=${DATADOG_API_KEY:}
management.datadog.metrics.export.application-key=${DATADOG_APP_KEY:}
management.datadog.metrics.export.step=1m
management.datadog.metrics.export.uri=${DATADOG_URI:https://api.datadoghq.com}
management.metrics.tags.modulo=Logistica
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# cola de mensajes

queue.host=jackal.rmq.cloudamqp.com
queue.username=vnfuxbdr
queue.password=Rb_2FdMdZG2INVFVrh4yDIyiPbfU859A
queue.name=cola_donaciones
