# Posrgres Database Configuration

# local
#spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
#spring.datasource.username=postgres
#spring.datasource.password=1234

# render

spring.datasource.url=jdbc:postgresql://dpg-d8l08pbtqb8s73al2bvg-a.ohio-postgres.render.com:5432/logistica_hj50
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=logistica_user
spring.datasource.password=jVfjegtNYU87o3EpVJtmBEnl5p0DUwco
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Datadog
management.datadog.metrics.export.uri=https://api.datadoghq.com/
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.api-key=2406e26896fe53e3e7d5b2065c723d66
management.datadog.metrics.export.applicationKey=ddapp_YlsFj6ZtIXqXlTBfVcoVtkyJPHzh4cOX6w

#management.datadog.metrics.export.uri=https://api.datadoghq.com/
#management.datadog.metrics.export.enabled=true
#management.datadog.metrics.export.step=30s
#management.datadog.metrics.export.api-key=6b4af422f0aae09dff0df439ab873c80
#management.datadog.metrics.export.applicationKey=ddapp_wR3lFSs0Pk3wUEEMpabToXyU1sFF2s1wBR

management.metrics.tags.modulo=logistica


spring.jpa.properties.hibernate.format_sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.tomcat.accesslog.enabled=true


server.port=${PORT:8080}
url.donaciones=http://localhost:8081 
url.donadoresYEntidades=http://localhost:8082
url.incentivos=http://localhost:8083
